#!/bin/bash
pyxbgen --schema-location=CGML1_0/CityGML.xsd --module=cgml \
		--schema-location=CGML1_0/CityGML/cityGMLBase.xsd --module=cgmlbase_1_0 \
	    --schema-location=CGML1_0/CityGML/appearance.xsd --module=appearance_1_0 \
	    --schema-location=CGML1_0/CityGML/building.xsd --module=building_1_0 \
	    --schema-location=CGML1_0/CityGML/cityFurniture.xsd --module=cityFurniture_1_0 \
	    --schema-location=CGML1_0/CityGML/cityObjectGroup.xsd --module=cityObjectGroup_1_0 \
	    --schema-location=CGML1_0/CityGML/generics.xsd --module=generics_1_0 \
	    --schema-location=CGML1_0/CityGML/landUse.xsd --module=landUse_1_0 \
	    --schema-location=CGML1_0/CityGML/relief.xsd --module=relief_1_0 \
	    --schema-location=CGML1_0/CityGML/texturedSurface.xsd --module=texturedSurface_1_0 \
	    --schema-location=CGML1_0/CityGML/transportation.xsd --module=transportation_1_0 \
	    --schema-location=CGML1_0/CityGML/vegetation.xsd --module=vegetation_1_0 \
	    --schema-location=CGML1_0/CityGML/waterBody.xsd --module=waterBody_1_0 \
	    --schema-location=CGML2_0/CityGML/cityGMLBase.xsd --module=cgmlbase_2_0 \
	    --schema-location=CGML2_0/CityGML/appearance.xsd --module=appearance_2_0 \
	    --schema-location=CGML2_0/CityGML/bridge.xsd --module=bridge_2_0 \
	    --schema-location=CGML2_0/CityGML/building.xsd --module=building_2_0 \
	    --schema-location=CGML2_0/CityGML/cityFurniture.xsd --module=cityFurniture_2_0 \
	    --schema-location=CGML2_0/CityGML/cityObjectGroup.xsd --module=cityObjectGroup_2_0 \
	    --schema-location=CGML2_0/CityGML/generics.xsd --module=generics_2_0 \
	    --schema-location=CGML2_0/CityGML/landUse.xsd --module=landUse_2_0 \
	    --schema-location=CGML2_0/CityGML/relief.xsd --module=relief_2_0 \
	    --schema-location=CGML2_0/CityGML/texturedSurface.xsd --module=texturedSurface_2_0 \
	    --schema-location=CGML2_0/CityGML/transportation.xsd --module=transportation_2_0 \
	    --schema-location=CGML2_0/CityGML/tunnel.xsd --module=tunnel_2_0 \
	    --schema-location=CGML2_0/CityGML/vegetation.xsd --module=vegetation_2_0 \
	    --schema-location=CGML2_0/CityGML/waterBody.xsd --module=waterBody_2_0 \
	    --module-prefix=citygml \
	    --archive-to-file=cgml.wxs

